### ISSUE TITLE
Module parse failed. What "loader" will I need and how to configure?

### ISSUE THREAD

**Issue by beauhawkinson** [clabby/BaoView#3]
in ./env.json
Module parse failed: Unexpected token I in JSON at position 4 while parsing near '{
  INFURA_URI: "https:/...'
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
SyntaxError: Unexpected token I in JSON at position 4 while parsing near '{
  INFURA_URI: "https:/...'
    at JSON.parse (<anonymous>)
    at parseJson (/Users/hawk/BaoView/node_modules/json-parse-better-errors/index.js:7:17)
    at JsonParser.parse (/Users/hawk/BaoView/node_modules/webpack/lib/JsonParser.js:16:16)
    at /Users/hawk/BaoView/node_modules/webpack/lib/NormalModule.js:478:32
    at /Users/hawk/BaoView/node_modules/webpack/lib/NormalModule.js:356:12
    at /Users/hawk/BaoView/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/Users/hawk/BaoView/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at Array.<anonymous> (/Users/hawk/BaoView/node_modules/loader-runner/lib/LoaderRunner.js:205:4)
    at Storage.finished (/Users/hawk/BaoView/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:55:16)
    at /Users/hawk/BaoView/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:91:9

**Comment by clabby** [comment]
@Twonarly1 Sorry for taking so long to reply, have been busy with work. This is probably an issue with your node version and/or incorrect versions of dependencies. BaoView was originally built on node v12.8.1 due to an issue I was having with SASS and webpack, but once the next franchise comes out and I get back to work on this, I'll update to a newer version.

Just pushed a [commit](https://github.com/clabby/BaoView/commit/7ec0ff735fb2acffaab7dd03a3cf3f7952944f65) that changes env.json -> env.js as well in case that doesn't solve your issue.
